export default {

  ZONES_RECEIVED: 'ZONES_RECEIVED',
  ZONE_CREATED: 'ZONE_CREATED',
  SELECT_ZONE: 'SELECT_ZONE',

  //COMMENT ACTION TYPES
  COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
  COMMENT_CREATED: 'COMMENT_CREATED'
}


//ORDER: CONSTANTS -> ACTIONS -> REDUCERS (ACTIONS RECEIVED BY REDUCERS)
